/*
 * Angus Henry 
 * formhurricane.java
 * This program tells you tje speeds of sifferent categorys of hurricanes
 * 22/03/2018 & 23/03/2018
 */

package hurricane;

/**
 *
 * @author anhen3335
 */
public class formhurricane extends javax.swing.JFrame {

    /**
     * Creates new form formhurricane
     */
    public formhurricane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labeltitle = new javax.swing.JLabel();
        labelquestion = new javax.swing.JLabel();
        textanswer = new javax.swing.JTextField();
        buttondecide = new javax.swing.JButton();
        labelstatement = new javax.swing.JLabel();
        labeltruth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labeltitle.setFont(new java.awt.Font("Zorque", 0, 36)); // NOI18N
        labeltitle.setText("Hurricane Scale");

        labelquestion.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 12)); // NOI18N
        labelquestion.setText("Please Enter a Hurricane Scale (1-5):");

        textanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textanswerActionPerformed(evt);
            }
        });

        buttondecide.setText("Select");
        buttondecide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondecideActionPerformed(evt);
            }
        });

        labelstatement.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 12)); // NOI18N

        labeltruth.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(labeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(labelstatement, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(labelquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttondecide, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(labeltruth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textanswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttondecide, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(labelstatement, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labeltruth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textanswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textanswerActionPerformed

    private void buttondecideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondecideActionPerformed
        int cat;
        cat = Integer.parseInt (textanswer.getText());
        switch (cat)
        {
            case 1:
              labelstatement.setText ("Windspeeds for Category 1 are:");
              labeltruth.setText ("74-95 mph or 64-82 kt or 119-153 km/hr");
                   break;
            case 2:
                labeltruth.setText ("96-110 mph or 83-95 kt or 154-177 km/hr");
                labelstatement.setText ("Windspeeds for Category 2 are:");
                break;
            case 3:
               labeltruth.setText ("111-130 mph or 96-113 kt or 178-209 km/hr");
                labelstatement.setText ("Windspeeds for Category 3 are:");
                break;
            case 4:
              labeltruth.setText ("131-155 mph or 114-135 kt or 210-249 km/hr");
                labelstatement.setText ("Windspeeds for Category 4 are:");
                break;
            case 5:
              labeltruth.setText ("greater than 155 mph or 135 kt or 249 km/hr");
                labelstatement.setText ("Windspeeds for Category 5 are:");
                break;
            default: 
                labelstatement.setText ("Wow, that is not a category");
                labeltruth.setText ("There is no truth to tell you about, becasue it does not exist.");
                break;
                
        }
    }//GEN-LAST:event_buttondecideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formhurricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formhurricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formhurricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formhurricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formhurricane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttondecide;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelquestion;
    private javax.swing.JLabel labelstatement;
    private javax.swing.JLabel labeltitle;
    private javax.swing.JLabel labeltruth;
    private javax.swing.JTextField textanswer;
    // End of variables declaration//GEN-END:variables
}